DynamicDataAddUsingJavaScript/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DynamicDataAddUsingJavaScript.Models
{
    public class Course
    {
        public Course(int id, string name, int did)
        {
            this.Id = id;
            this.Name = name;
            this.DepartmentId = did;
        }

        public Course()
        {
            
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int DepartmentId { get; set; }
        public Department Department { get; set; }
        public List<Course> Courses { get; set; } 

        public List<Course> GetCourses()
        {
            List<Course> CourseList=new List<Course>();
            CourseList.Add(new Course(Id=1,Name="Math",DepartmentId=1));
            CourseList.Add(new Course(Id = 2, Name = "Computer Architecture", DepartmentId = 2));
            CourseList.Add(new Course(Id = 3, Name = "Software Engineering", DepartmentId = 1));
            CourseList.Add(new Course(Id = 4, Name = "Testing", DepartmentId = 3));
            CourseList.Add(new Course(Id = 5, Name = "Basic Electronics", DepartmentId = 4));
            return CourseList;
        } 
    }
}

DynamicDataAddUsingJavaScript/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DynamicDataAddUsingJavaScript.Models
{
    public class Department
    {
        public int  Id  { get; set; }
        public string Name { get; set; }
        public List<Department> Departments { get; set; } 

        public Department(int id,string name)
        {
            this.Id = id;
            this.Name = name;
        }

        public Department()
        {
        }

        public List<Department> GetDepartments()
        {
            List<Department> departmentList = new List<Department>();
            departmentList.Add(new Department(Id=1, Name="Computer Science And Engineering"));
            departmentList.Add(new Department(Id=2, Name = "Bachelor of Study"));
            departmentList.Add(new Department(Id=3, Name = "Bachelor of Arts"));
            departmentList.Add(new Department(Id=4, Name = "Bachelor Of Science"));
            return departmentList;
        } 
    }
}

DynamicDataAddUsingJavaScript/Models/Semester.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DynamicDataAddUsingJavaScript.Models
{
    public class Semester
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        
        public List<Department> Departments { get; set; } 
        public List<Course> Courses { get; set; } 
    }
}

DynamicDataAddUsingJavaScript/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DynamicDataAddUsingJavaScript.Models;

namespace DynamicDataAddUsingJavaScript.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course
        public ActionResult Index()
        {
            Course c=new Course();
            Department d=new Department();
            ViewBag.DepartmentId = new SelectList(d.GetDepartments(), "Id", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Index(Course course)
        {
            Course c = new Course();
            c.Courses.Add(course);
            Department d = new Department();
            ViewBag.DepartmentId = new SelectList(d.GetDepartments(), "Id", "Name");
            return View();
        }

        public JsonResult GetByDepartment(int? departmentId)
        {
            Course c=new Course();
            if (departmentId == null)
            {
                return null;
            }
            var Courses = c.GetCourses().Where(d => d.DepartmentId == departmentId).ToList();
            return Json(Courses, JsonRequestBehavior.AllowGet);
        }
    }
}

DynamicDataAddUsingJavaScript/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DynamicDataAddUsingJavaScript.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

DynamicDataAddUsingJavaScript/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using DynamicDataAddUsingJavaScript.Models;

namespace DynamicDataAddUsingJavaScript.Controllers
{
    public class SemesterController : Controller
    {
        // GET: Student
        [HttpGet]
        public ActionResult Index()
        {
            Department department=new Department();
            Course course=new Course();
            Semester semester=new Semester();
            semester.Departments = department.GetDepartments();
            ViewBag.DepartmentDropDown=new SelectList(semester.Departments,"Id","Name");
            semester.Courses = course.GetCourses();
            ViewBag.CourseDropDown = new SelectListItem[] { new SelectListItem() { Value = "", Text = "Select..." } };
            return View();
        }
        [HttpPost]
        public ActionResult Index(Semester semester)
        {

            Department department = new Department();
            Course course = new Course();
            Semester sem=new Semester();
            sem.Departments = department.GetDepartments();
            ViewBag.DepartmentDropDown = new SelectList(sem.Departments, "Id", "Name");
            sem.Courses = course.GetCourses();
            ViewBag.CourseDropDown = new SelectListItem[] { new SelectListItem() { Value = "", Text = "Select..." } };
            return View();
        }
    }
}

DynamicDataAddUsingJavaScript/Views/Course/Index.cshtml
@model DynamicDataAddUsingJavaScript.Models.Course

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Index","Course",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", null, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DynamicDataAddUsingJavaScript/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

DynamicDataAddUsingJavaScript/Views/Semester/Index.cshtml
@model DynamicDataAddUsingJavaScript.Models.Semester

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new {htmlAttributes = new {@class = "form-control",id="semesterName"}})
                @Html.ValidationMessageFor(model => model.FullName, "", new {@class = "text-danger"})
            </div>
        </div>

       

    <div class="form-group">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="form-group">
                            @Html.Label("Category", htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-8">
                                @Html.DropDownList("DepartmentDropDown", null, htmlAttributes: new {@class = "dropdown form-control", id = "departmentDD"})
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Course", htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-8">
                                @Html.DropDownList("CourseDropDown", null, htmlAttributes: new {@class = "dropdown form-control", id = "courseDD"})
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="button" value="Add" class="btn btn-default" onclick="AddData()" id="addButton"/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>Name Of Department</th>
                                        <th>Name Of Course</th>
                                        <th>Name Of Semester</th>
                                    </tr>
                                    </thead>
                                    <tbody id="tblBody">
                                    
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                    
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                 

                    </div>
                </div>
            </div>
        </div>



}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section scripts
{
    <script src="~/scripts/Student/studentCreate.js"></script>
}

DynamicDataAddUsingJavaScript/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            </ul>
        </div>
    </div>
</div>

<div class="container body-content">
    @RenderBody()
    <hr/>

    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

    <script src="~/scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>